# Generated by Django 2.0.4 on 2018-08-15 14:56

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField()),
                ('wiki_id', models.IntegerField()),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('other_spellings', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('pronunciations', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition_txt', models.TextField(null=True)),
                ('definition_xml', models.TextField(null=True)),
                ('definition_CoNLL', models.TextField(null=True)),
                ('labels', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example_txt', models.TextField(null=True)),
                ('example_xml', models.TextField(null=True)),
                ('example_CoNLL', models.TextField(null=True)),
                ('labels', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='words.Definition')),
            ],
        ),
        migrations.CreateModel(
            name='Pos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronunciations', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('inflections', django.contrib.postgres.fields.jsonb.JSONField()),
                ('paradigms', django.contrib.postgres.fields.jsonb.JSONField()),
                ('translations', django.contrib.postgres.fields.jsonb.JSONField()),
                ('subsections', django.contrib.postgres.fields.jsonb.JSONField()),
                ('word_type', models.CharField(max_length=30)),
                ('lemma', models.BooleanField()),
                ('locution', models.BooleanField()),
                ('gender', models.CharField(choices=[('m', 'm'), ('f', 'f'), ('e', 'e'), ('inconsistentGender', 'inconsistentGender')], max_length=1, null=True)),
                ('number', models.CharField(choices=[('s', 'singular'), ('p', 'plural'), ('sp', 'invariable'), ('singulareTantum', 'singulareTantum'), ('pluraleTantum', 'pluraleTantum'), ('inconsistentNumber', 'inconsistentNumber')], max_length=15, null=True)),
                ('equivMasc', models.TextField(null=True)),
                ('equivFem', models.TextField(null=True)),
                ('demonym', models.NullBooleanField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poses', to='words.Article')),
            ],
        ),
        migrations.AddField(
            model_name='definition',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='words.Pos'),
        ),
    ]
